controllers:
    resource: ../src/Controller/
    type: annotation



app_login:
    path: /login
    controller: App\Controller\SecurityController::login

homepage:
    path: /
    controller: App\Controller\HomeController::index

subscription:
    path: /subscription
    controller: App\Controller\SubscriptionController::Subscription

pdf_generation:
    path: /pdf
    controller: App\Controller\PdfController::generatePdf

history:
    path: /history
    controller: App\Controller\HistoryController::index

